<?php
    namespace App\Libraries;
    use Ataccama\Adapters\Utils\UserProfile;
    use Ataccama\Auth\Auth;
    use Ataccama\Utils\RefreshToken;

    class Authkeycloak extends Auth{
        public function getLoginUrl(): string
        {
            return parent::getLoginUrl(); // TODO: Change the autogenerated stub
        }

        public function isAuthorized(): bool
        {
            // TODO: Implement isAuthorized() method.
        }
        public function getRefreshToken(): RefreshToken
        {
            // TODO: Implement getRefreshToken() method.
        }
        public function authorized(UserProfile $userProfile): bool
        {
            // TODO: Implement authorized() method.
        }
        public function getRedirectUri(): string
        {
            // TODO: Implement getRedirectUri() method.
        }

        public function setAuthorized(bool $authorized): bool
        {
            // TODO: Implement setAuthorized() method.
        }
    }